
import InputerVerifierClass.ValidateRegularExpression;
import cla.DataCon;
import cla.DateConvertion;
import cla.MyInput;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer 4738
 */
public class tableStaff extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public tableStaff() {
        initComponents();
        txtEmail.setInputVerifier(new ValidateRegularExpression(txtEmail,"^[A-Z0-9._%-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}$","Invalied email"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtWorkTypeID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        rFemale = new javax.swing.JRadioButton();
        rMale = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        DatePickerSettings dateSettings=new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("dd / MM / yyyy");
        dateSettings.setFormatForDatesBeforeCommonEra("dd / MM/ uuuu");
        txtDoB = new com.github.lgooddatepicker.components.DatePicker(dateSettings);
        txtPostion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtWorkType = new javax.swing.JComboBox<>();
        txtPositionID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTel = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtSalary = new subtextfield.SubTextField();
        btnCommit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAllStaff = new subjtable.SubJTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAdding = new subjtable.SubJTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Name");

        txtName.setName("Name"); // NOI18N
        txtName.setNextFocusableComponent(rMale);

        jLabel3.setText("Date of birth");

        jLabel4.setText("Address");

        txtAddress.setName("Address"); // NOI18N

        jLabel5.setText("Tel");

        jLabel6.setText("Position");

        txtWorkTypeID.setEditable(false);
        txtWorkTypeID.setName("Position"); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonGroup1.add(rFemale);
        rFemale.setText("Female");

        buttonGroup1.add(rMale);
        rMale.setSelected(true);
        rMale.setText("Male");

        jLabel2.setText("Gender");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        txtDoB.setName("Date of Birth"); // NOI18N

        txtPostion.setNextFocusableComponent(txtWorkType);
        txtPostion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPostionActionPerformed(evt);
            }
        });

        jLabel7.setText("Positon ID");

        jLabel8.setText("Work Type");

        jLabel9.setText("Work Typy ID");

        txtWorkType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkTypeActionPerformed(evt);
            }
        });

        txtPositionID.setEditable(false);
        txtPositionID.setName("Position"); // NOI18N

        jLabel10.setText("Email");

        txtEmail.setName("Address"); // NOI18N

        jLabel11.setText("Salary");

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtSalary.setFloatOnly(true);
        txtSalary.setName("Salary"); // NOI18N

        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tableAllStaff.setAutoCreateRowSorter(true);
        tableAllStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Date Of Birth", "Address", "Tel", "Email", "Salary", "Position", "WorkType"
            }
        ));
        tableAllStaff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableAllStaff.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tableAllStaff);
        tableAllStaff.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTabbedPane1.addTab("All Staff", jScrollPane2);

        tableAdding.setAutoCreateRowSorter(true);
        tableAdding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Date Of Birth", "Address", "Tel", "Email", "Salary", "PositionID", "Position", "WorkTypeID", "WorkType"
            }
        ));
        tableAdding.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(tableAdding);
        tableAdding.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTabbedPane1.addTab("Adding", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTel)
                                    .addComponent(txtAddress))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPositionID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWorkTypeID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtPostion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(rMale)
                .addGap(18, 18, 18)
                .addComponent(rFemale)
                .addContainerGap(1003, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPositionID, txtPostion, txtWorkType, txtWorkTypeID});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rFemale)
                            .addComponent(rMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPostion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPositionID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtWorkType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnCommit)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(btnDel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAddress, txtEmail, txtName, txtPositionID, txtPostion, txtTel, txtWorkType, txtWorkTypeID});

        btnAdd.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String emptyFieldName=MyInput.checkEmptyFieldName(txtName,txtSalary,txtAddress,txtTel,txtEmail);
        System.out.println(emptyFieldName); 
       if(emptyFieldName==null){
            String name=txtName.getText();          
            String address=txtAddress.getText();
            String gender;
            if(rMale.isSelected()){
                gender="Male";
            }else{
                gender="Female";
            }
            String tel=""+txtTel.getText().replaceAll("[^\\.0123456789]","");
            String email=txtEmail.getText();
            String salary=txtSalary.getText();
            String poID=txtPositionID.getText();
            String po=txtPostion.getSelectedItem().toString();
            String wType=txtWorkType.getSelectedItem().toString();
            String wTypeID=txtWorkTypeID.getText();
            String dateOfBirth=txtDoB.getText();
            String staff[]={name, gender,dateOfBirth, address,tel,email,salary,poID,po,wTypeID,wType};
            tableAdding.addRow(staff);
       }else{
            JOptionPane.showMessageDialog(this, "You haven\'t enter field \""+emptyFieldName+"\"");
        }
     
    }//GEN-LAST:event_btnAddActionPerformed
    private void setDataInfo(){
        txtName.setText("");
        if (true) {
            rFemale.setSelected(true);
        } else {
            rMale.setSelected(true);
        }
        txtSalary.setText("");
        txtTel.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtPostion.setSelectedIndex(-1);
        txtWorkType.setSelectedIndex(-1);
    }
    private void addItemToComboBox(){
        try {
            try (Statement s = DataCon.getDataCon().createStatement()) {
                ResultSet r=s.executeQuery("SELECT worktype FROM worktype");
                if(r.first()){
                    do{
                        txtWorkType.addItem(r.getString(1));
                    }while (r.next());
                }
                r=s.executeQuery("SELECT position FROM position");
                if(r.first()){
                    do{
                        txtPostion.addItem(r.getString(1));
                    }while (r.next());
                }
                r.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }
    private void addTableData(){
        try(Statement s = DataCon.getDataCon().createStatement();
                ResultSet r = s.executeQuery("SELECT * FROM `vwtablestaff`")) {
            tableAllStaff.addRowResultSet(r);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        addItemToComboBox(); 
        addTableData();
        txtDoB.setDateToToday();
        tableAllStaff.setColumnWidthRatio(1,3,1,2,2,2,3,2,2,2,2,2);
        tableAdding.setColumnWidthRatio(3,1,2,2,2,3,2,2,2,2,2);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_formWindowOpened

    private void txtPostionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPostionActionPerformed
        try {
            System.out.println(txtPostion.getSelectedItem());
            try (Statement s = DataCon.getDataCon().createStatement(); 
                        ResultSet r = s.executeQuery("SELECT positionid FROM position WHERE position='" + txtPostion.getSelectedItem() + "'")) {
                if (r.first()) {
                    txtPositionID.setText(r.getString(1));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtPostionActionPerformed

    private void txtWorkTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkTypeActionPerformed
        try {
            try (Statement s = DataCon.getDataCon().createStatement(); ResultSet r = s.executeQuery("SELECT worktypeid FROM worktype WHERE worktype='"+txtWorkType.getSelectedItem()+"'")) {
                if(r.first())
                    txtWorkTypeID.setText(r.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtWorkTypeActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        try {
            try (Statement s = DataCon.getDataCon().createStatement()) {
                for(int i=0;i<tableAdding.getRowCount();i++){
                    String name = ""+tableAdding.getValueAt(i, 0);
                    String gender=""+tableAdding.getValueAt(i, 1);
                    String dateOfBirth=DateConvertion.convertDate(tableAdding.getValueAt(i, 2));
                    String address = ""+tableAdding.getValueAt(i, 3);
                    String tel = ""+tableAdding.getValueAt(i, 4);
                    String email = ""+tableAdding.getValueAt(i, 5);
                    String salary = ""+tableAdding.getValueAt(i, 6);
                    String poID = ""+tableAdding.getValueAt(i, 7);
                    String wTypeID = ""+tableAdding.getValueAt(i, 9);
                    s.execute("INSERT INTO sa_project.staff (\n"
                            + "	staff.SName,\n"
                            + "	staff.Sex,\n"
                            + "	staff.DoB,\n"
                            + "	staff.Address,\n"
                            + "	staff.Tel,\n"
                            + "	staff.Email,\n"
                            + "	staff.Salary,\n"
                            + "	staff.PositionID,\n"
                            + "	staff.WorkTypeID\n"
                            + ")\n"
                            + "VALUES\n"
                            + "	(\n"
                            + "		'"+name+"',\n"
                            + "		'"+gender+"',\n"
                            + "		'"+dateOfBirth+"',\n"
                            + "		'"+address+"',\n"
                            + "		'"+tel+"',\n"
                            + "		'"+email+"',\n"
                            + "		'"+salary+"',\n"
                            + "		'"+poID+"',\n"
                            + "		'"+wTypeID+"'\n"
                            + "	);");
                    tableAdding.removeRow(i);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnCommitActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int option=JOptionPane.showConfirmDialog(this, "Do you want to delete this recode");
        if(option==JOptionPane.YES_OPTION){
            if(jTabbedPane1.getSelectedIndex()==1){
                tableAdding.removeSelectedRows();
            }else{
                try (Statement s=DataCon.getDataCon().createStatement()){
                    int rowToDelete=tableAllStaff.getSelectedRow();
                    s.execute("DELETE FROM staff where SID="+ tableAllStaff.getValueAt(rowToDelete, 0));
                    tableAllStaff.removeRow(rowToDelete);
                    
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tableAllStaff.clearRecord();
        addTableData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tableStaff().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnDel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale;
    private subjtable.SubJTable tableAdding;
    private subjtable.SubJTable tableAllStaff;
    private javax.swing.JTextField txtAddress;
    private com.github.lgooddatepicker.components.DatePicker txtDoB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPositionID;
    private javax.swing.JComboBox<String> txtPostion;
    private subtextfield.SubTextField txtSalary;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JComboBox<String> txtWorkType;
    private javax.swing.JTextField txtWorkTypeID;
    // End of variables declaration//GEN-END:variables
}
